// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: test/proto/grpcfd_test.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	FDService_ServerReceive_FullMethodName = "/test_proto.FDService/ServerReceive"
	FDService_ServerSend_FullMethodName    = "/test_proto.FDService/ServerSend"
)

// FDServiceClient is the client API for FDService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FDServiceClient interface {
	ServerReceive(ctx context.Context, in *FD, opts ...grpc.CallOption) (*FD, error)
	ServerSend(ctx context.Context, in *FD, opts ...grpc.CallOption) (*FD, error)
}

type fDServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFDServiceClient(cc grpc.ClientConnInterface) FDServiceClient {
	return &fDServiceClient{cc}
}

func (c *fDServiceClient) ServerReceive(ctx context.Context, in *FD, opts ...grpc.CallOption) (*FD, error) {
	out := new(FD)
	err := c.cc.Invoke(ctx, FDService_ServerReceive_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fDServiceClient) ServerSend(ctx context.Context, in *FD, opts ...grpc.CallOption) (*FD, error) {
	out := new(FD)
	err := c.cc.Invoke(ctx, FDService_ServerSend_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FDServiceServer is the server API for FDService service.
// All implementations must embed UnimplementedFDServiceServer
// for forward compatibility
type FDServiceServer interface {
	ServerReceive(context.Context, *FD) (*FD, error)
	ServerSend(context.Context, *FD) (*FD, error)
	mustEmbedUnimplementedFDServiceServer()
}

// UnimplementedFDServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFDServiceServer struct {
}

func (UnimplementedFDServiceServer) ServerReceive(context.Context, *FD) (*FD, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServerReceive not implemented")
}
func (UnimplementedFDServiceServer) ServerSend(context.Context, *FD) (*FD, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServerSend not implemented")
}
func (UnimplementedFDServiceServer) mustEmbedUnimplementedFDServiceServer() {}

// UnsafeFDServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FDServiceServer will
// result in compilation errors.
type UnsafeFDServiceServer interface {
	mustEmbedUnimplementedFDServiceServer()
}

func RegisterFDServiceServer(s grpc.ServiceRegistrar, srv FDServiceServer) {
	s.RegisterService(&FDService_ServiceDesc, srv)
}

func _FDService_ServerReceive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FD)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FDServiceServer).ServerReceive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FDService_ServerReceive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FDServiceServer).ServerReceive(ctx, req.(*FD))
	}
	return interceptor(ctx, in, info, handler)
}

func _FDService_ServerSend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FD)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FDServiceServer).ServerSend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FDService_ServerSend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FDServiceServer).ServerSend(ctx, req.(*FD))
	}
	return interceptor(ctx, in, info, handler)
}

// FDService_ServiceDesc is the grpc.ServiceDesc for FDService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FDService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "test_proto.FDService",
	HandlerType: (*FDServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ServerReceive",
			Handler:    _FDService_ServerReceive_Handler,
		},
		{
			MethodName: "ServerSend",
			Handler:    _FDService_ServerSend_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test/proto/grpcfd_test.proto",
}
